# Generated by Django 4.0.4 on 2022-05-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Membro', 'verbose_name_plural': 'Membros'},
        ),
        migrations.AddField(
            model_name='team',
            name='facebook',
            field=models.URLField(blank=True, default='#', verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='team',
            name='github',
            field=models.URLField(blank=True, default='#', verbose_name='Github'),
        ),
        migrations.AddField(
            model_name='team',
            name='instagram',
            field=models.URLField(blank=True, default='#', verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='team',
            name='linkedin',
            field=models.URLField(blank=True, default='#', verbose_name='Linkedin'),
        ),
        migrations.AddField(
            model_name='team',
            name='twitter',
            field=models.URLField(blank=True, default='#', verbose_name='Twitter'),
        ),
    ]
