# Generated by Django 4.0.4 on 2022-05-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_team_options_team_facebook_team_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='facebook',
            field=models.CharField(blank=True, default='#', max_length=100, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='team',
            name='github',
            field=models.CharField(blank=True, default='#', max_length=100, verbose_name='Github'),
        ),
        migrations.AlterField(
            model_name='team',
            name='instagram',
            field=models.CharField(blank=True, default='#', max_length=100, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='team',
            name='linkedin',
            field=models.CharField(blank=True, default='#', max_length=100, verbose_name='Linkedin'),
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter',
            field=models.CharField(blank=True, default='#', max_length=100, verbose_name='Twitter'),
        ),
    ]
