# Generated by Django 4.0.4 on 2022-05-10 12:21

import core.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_team_facebook_alter_team_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='member_photo',
            field=stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='Foto'),
        ),
    ]
